export const NOUNS = {
  IP: "IP",
  ROLE: "Role",
  ROLE_NAME: "Role Name",
  MANUFACTURE: "Manufacturer",
  PRODUCT: "Product",
  PHONE_NUMBER: "Phone Number",
  EMAIL: "Email",
  CATEGORY: "Category",
  TAG: "Tag",
  USERNAME: "Username",
  USERNAME_OR_EMAIL: "Username or Email",
  DESCRIPTION: "Description",
  PERMISSION: "Permission",
  USER: "User",
  USERS: "Users",
  SIGNIN: "Sign In",
  PHONENUMBER: "Phone Number",
  MANUFACTURER: "Manufacturer",
  SHOPPINGCART: "Shopping Cart",
  WALLET: "Wallet",
  SPECIFICATION_OPTION: "Specification Option",
  SPECIFICATION: "Specification",
  PRODUCT_SPECIFICATION: "Product Specification",
  ACTIVATION_CODE: "Activation Code",
  CUSTOMER: "Customer",
  CUSTOMERS: "Customers",
  FAVORITE_PRODUCT: "Favorite Product",
  COMMENT: "Comment",
  SIGNUPTEXT: "Do not you have an account?",
  SIGNUPBUTTON: "Create a account",
  FIRSTNAME: "First Name",
  LASTNAME: "Last Name",
  FULLNAME: "Full Name",
  PROFILE: "Profile",
  BIRTH_DATE: "Birth Date",
  GENDER: "Gender",
  PASSWORD: "Password",
  FORGETPASSWORD: "Forget Password ? ",
  NEW_PASSWORD: "New Password",
  COUPON_CODE: "Coupon Code",
  CODE: "Code",
  PARENT_CATEGORY: "Parent Category",
  META_KEYWORD: "Meta Keyword",
  META_TITLE: "Meta Title",
  NAME_EN: "Name English",
  DISCOUNT: "Discount",
  DISCOUNT_COUPON: "Discount Coupon",
  DISCOUNT_AMOUNT: "Discount Amount",
  DISCOUNT_PERCENTAGE: "Discount Percentage",
  MAX_DISCOUNT_AMOUNT: "Maximum Discount Amount",
  MAX_USAGE: "Maximum Usage",
  DISPLAY_ORDER: "Display Order",
  ADDRESS: "Address",
  POSTAL_CODE: "Postal Code",
  PROVINCE: "Province",
  PROVINCE_NAME: "Province Name",
  PROVINCE_ID: "Province ID",
  CITY: "City",
  CITY_NAME: "City Name",
  COUNTRY: "Country",
  COUNTRY_NAME: "Country Name",
  COUNTRY_ID: "Country ID",
  LONGITUDE: "Longitude",
  LATITUDE: "Latitude",
  NAME: "Name",
  PAGE: "Page",
  IMAGE_FORMAT: "Image Format",
  VIDEO_FORMAT: "Video Format",
  FILE_FORMAT: "File Format",
  FILE: "File",
  IMAGE: "Image",
  IMAGES: "Images",
  IMAGE_TITLE: "Image Title",
  IMAGE_ALT: "Image Alt",
  IMAGE_DESCRIPTION: "Image Description",
  VIDEO: "Video",
  VIDEOS: "Videos",
  VIDEO_TITLE: "Video Title",
  VIDEO_DESCRIPTION: "Video Description",
  SLIDER: "Slider",
  BANNER: "Banner",
  SETTINGS: "Settings",
  SMS: "SMS",
  SUBJECT: "Subject",
  BODY: "Body",
  START_DATE: "Start Date",
  END_DATE: "End Date",
  DAILY_OFFER: "Daily Offer",
  DATE: "Date",
  RESET_PASS_REQUEST: "Reset Pass Request",
  PASS_REQUEST_CODE: "Password Request Code",
  PUSH_NOTIFICATION: "Push Notification",
  TITLE: "Title",
  PRIORITY: "Priority",
  SHOW_APP: "Show App",
  QUANTITY: "Quantity",
  INPUT: "Input",
  CREDIT: "Credit",
  IS_ACTIVE: "Is Active",
  IS_SYSTEM_ROLE: "Is System Role",
  ARRAY: "Array",
  PUSH_ID: "Push ID",
  HOUR: "Hour",
  MINUTES: "Minutes",
  SECONDS: "Seconds",
  LIMIT: "Limit",
  PRICE: "Price",
  COST: "Cost",
  TRANSACTION: "Transaction",
  AMOUNT: "Amount",
  zarinpal: "Zarinpal", // should be written in small letters
  SELL_COUNT: "Sell Count",
  ISPERCENTAGE: "Is Percentage",
  COUPONCODE: "Coupon Code",
  DISCOUNTPERCENTAGE: "Discount Percentage",
  DISCOUNTAMOUNT: "Discount Amount",
  MAXDISCOUNTAMOUNT: "Maximum Discount Amount",
  PAID_DATE: "Paid Date",
  COUPON_CODE_DISCOUNT: "Coupon Code Discount",
  ORDER_STATE_ID: "Order State ID",
  PAYMENT_STATUS_ID: "Payment Status ID",
  PAYMENT_TYPE: "Payment Type",
  CUSTOMER_CURRENCY_CODE: "Customer Currency Code",
  ORDER_DISCOUNT: "Order Discount",
  ORDER_TOTAL: "Order Total",
  NUMBER: "Number",
  INVOICE_NUMBER: "Invoice Number",
  EMAIL_VERIFICATION: "Email Verification",
  YOUR_GENERATED_PASSWORD: "Your Generated Password",
  EMAIL_CHANGED_NOTIFICATION: "Email Changed Notification",
  PASSWORD_CHANGED_NOTIFICATION: "Password Changed Notification",
  PASSWORD_RESET_CODE: "Password Reset Code",
  HEADING: "Heading",
  HEADING_CONTENT: "Heading Content",
  QUESTION: "Question",
  ANSWER: "Answer",
  PAGE_TITLE: "Page Title",
  JOB_TITLE: "Job Title",
  JOB_DESCRIPTION: "Job Description",
  QUALIFICATIONS: "Qualifications",
  DUTIES: "Duties",
  MARITAL_STATUS: "Marital Status",
  CONTACT_NUMBER: "Contact Number",
  MILITARY_SERVICE_STATUS: "Military Service Status",
  FILE_ID: "File ID",
  RESUME: "Resume",
  ACTIVE_TOKEN: "Active Token",
  SEARCH: "Search",
  USER_TYPE: "User Type",
  ORDER: "Order",
  IS_PRIVATE_STATE: "Is Private State",
  MONTH: "Month",
  VALUE: "Value",
  RECAPTCHA: "Recaptcha",
  NEW_EVENTS: "New Events",
  RESTRICTIVE_FIELD: "Restrictive Field",
  VERIFICATION_CODE: "Verification Code",
  TIME: "Time",
  NEWSLETTER_CALL: "Newsletter Call",
  NEWSLETTER_SMS: "Newsletter SMS",
  NEWSLETTER_EMAIL: "Newsletter Email",
  IS_DEFAULT: "Is Default",
  RECEIPT: "Receipt",
  MODEL_NAME: "Model Name",
  MESSAGE: "Message",
  STATUS: "Status",
  TICKET: "Ticket",
  CONTACT_FORM: "Contact Form",
  ANNOUNCEMENT: "Announcement",
  WELCOME: "Welcome !",
  SUCCESS: "success",
  WARNING: "warning",
  ERROR: "error",
  CLICK_HERE: "Click here",
  CREATE_ACCOUNT: "Create Account",
  FULL_NAME: "Full name",
  SIGN_UP: "Sign up",
  ALREADY_HAVE_AN_ACCOUNT: "Already have an account ?",
  VERIFICATION_EMAIL_SEND: "Verification email sent",
  VERIFICATION_EMAIL_NOT_SEND: "Failed to resend verification email",
  VERIFY_EMAIL: "Verify Email",
  VERIFICATION_CODE: "Verification Code",
  VERIFY: "Verify",
  RESEND_CODE: "Resend code",
  RECAPTCHA_FAILED: "Failed to load reCAPTCHA",
  RESET_PASSWORD: "Reset Password",
  RESET: "RESET",
  BACK: "Back",
  OR: "Or",
  PASSWORDRETRY: "Password Retry",
};
