import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/lib/SessionProvider";
import { dbConnect } from "@/lib/mongo";
import { Toaster } from "react-hot-toast";
import Image from "next/image";
import bgImage from "@/assets/image/background.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Renosa Tech",
  description: "Generated by Akbar Rasi Rahimi",
};

export default async function RootLayout({ children: children }: { children: React.ReactNode }) {
  await dbConnect();
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="mytheme">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="flex h-screen w-screen items-center justify-center text-xs">
            <Toaster position="top-right" />
            <div className="bg-neutral-focus relative flex h-screen w-screen flex-col items-center justify-center">
              <Image src={bgImage} alt="bg" className="w-full h-full object-cover absolute top-0 left-0 " />
              <div className="absolute bg-transparent bottom-0 left-0 w-screen">
                <svg
                  className="h-16 w-full"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlnsXlink="http://www.w3.org/1999/xlink"
                  viewBox="0 24 150 28"
                  preserveAspectRatio="none"
                  shapeRendering="auto">
                  <defs>
                    <path
                      id="gentle-wave"
                      d="M-160 44c30 0 58-18 88-18s58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
                  </defs>
                  <g className="parallax">
                    <use xlinkHref="#gentle-wave" x="48" y="7" fill="#2553A3" className="waves-animation "></use>
                  </g>
                </svg>
              </div>
              {children}
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
